### ISSUE TITLE
SRC_DIR cannot be used in conda-build test section any more

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-Py#922]
This is a new change made by `conda-build` (https://github.com/conda/conda-build/pull/1630). Basically, the source files (SRC_DIR) will be deleted right before testing phase starts for some safety purpose. However, RMG-Py and other RMG related pkgs (like `openbabel` in `conda-recipes`) are still using `SRC_DIR` in testing phase, e.g. in the `meta.yaml` of `RMG-Py`

```
test:
  requires:
    - nose
  imports:
    - rmgpy
commands:
    - cp $PREFIX/lib/python2.7/site-packages/rmgpy/rmgrc $SRC_DIR [unix]
    - make -C $SRC_DIR test [unix]
```

and `meta.yaml` of `openbabel`:

```
test:
  imports:
    - openbabel
    - pybel
  commands:
    - cd $SRC_DIR/test ; python test_pybel.py [unix]
    - cd $SRC_DIR/test ; python testbabel.py [unix]
    - cd $SRC_DIR/test ; python testkekule.py [unix]
    - cd $SRC_DIR/test ; python testbindings.py [unix]
```

Which already starts causing troubles for new binary generations. New recipes will be updated soon.
